name: CI/CD Pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Installer les dépendances Composer
        run: composer install

      - name: Lancer les tests PHPUnit
        run: vendor/bin/phpunit tests

      - name: Builder l'image Docker
        run: docker build -t salehterefi/projet-ci-cd .

      - name: Connexion à Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pousser l'image sur Docker Hub
        run: docker push salehterefi/projet-ci-cd